#pragma once

#define NUMBEROFSLOTS 4
#define PIN_CLOCK 33
#define PIN_BACKBUTTON 32
#define PIN_CONFIRMBUTTON 34
#define PIN_ROTARY 35

#define PIN_LED_SLOT0 26
#define PIN_LED_SLOT1 27
#define PIN_LED_SLOT2 30
#define PIN_LED_SLOT3 31

#define DEBOUNCETIME_BUTTON 20
